-- Operational foundation for the coordinator MVP.

alter table shifts
  add column if not exists timezone text not null default 'Europe/London';

create table if not exists audit_events (
  id           bigint generated by default as identity primary key,
  event_type   text not null,
  shift_id     uuid references shifts (id) on delete set null,
  volunteer_id uuid references volunteers (id) on delete set null,
  metadata     jsonb not null default '{}'::jsonb,
  created_at   timestamptz not null default now()
);

create table if not exists notification_log (
  id                  bigint generated by default as identity primary key,
  shift_id            uuid not null references shifts (id) on delete cascade,
  volunteer_id        uuid references volunteers (id) on delete set null,
  recipient           text not null,
  notification_type   text not null check (
    notification_type in ('shift_alert', 'claim_confirmation', 'coordinator_claim_notice')
  ),
  delivery_status     text not null check (delivery_status in ('sent', 'failed')),
  provider_message_id text,
  error_message       text,
  created_at          timestamptz not null default now()
);

create index if not exists idx_audit_events_shift_created
  on audit_events (shift_id, created_at desc);

create index if not exists idx_notification_log_shift_created
  on notification_log (shift_id, created_at desc);

alter table audit_events enable row level security;
alter table notification_log enable row level security;

-- Explicitly remove browser-facing table privileges. The service role operates
-- on the server and bypasses RLS.
revoke all on table volunteers, shifts, claim_tokens, audit_events, notification_log
  from anon, authenticated;

-- Replace the initial claim function with a version that locks both the token
-- and the shift, returns identifiers needed for notifications, and records the
-- successful assignment in the same database transaction.
create or replace function claim_shift(p_token uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_token claim_tokens%rowtype;
  v_shift shifts%rowtype;
begin
  select *
    into v_token
    from claim_tokens
   where token = p_token
   for update;

  if not found then
    return jsonb_build_object('status', 'invalid_token');
  end if;

  if v_token.used_at is not null then
    return jsonb_build_object('status', 'token_used');
  end if;

  if v_token.expires_at <= now() then
    return jsonb_build_object('status', 'expired');
  end if;

  select *
    into v_shift
    from shifts
   where id = v_token.shift_id
   for update;

  if not found then
    return jsonb_build_object('status', 'invalid_token');
  end if;

  if v_shift.status <> 'open' then
    return jsonb_build_object(
      'status', 'already_claimed',
      'shift_id', v_shift.id,
      'shift_title', v_shift.title
    );
  end if;

  if v_shift.starts_at <= now() then
    update shifts set status = 'expired' where id = v_shift.id;
    return jsonb_build_object('status', 'expired', 'shift_id', v_shift.id);
  end if;

  update shifts
     set status = 'claimed',
         claimed_by = v_token.volunteer_id,
         claimed_at = now()
   where id = v_shift.id;

  update claim_tokens
     set used_at = now()
   where token = p_token;

  insert into audit_events (event_type, shift_id, volunteer_id, metadata)
  values (
    'shift_claimed',
    v_shift.id,
    v_token.volunteer_id,
    jsonb_build_object('token_created_at', v_token.created_at)
  );

  return jsonb_build_object(
    'status', 'claimed',
    'shift_id', v_shift.id,
    'volunteer_id', v_token.volunteer_id,
    'shift_title', v_shift.title,
    'starts_at', v_shift.starts_at
  );
end;
$$;

revoke all on function claim_shift(uuid) from public, anon, authenticated;
grant execute on function claim_shift(uuid) to service_role;
